version: '3.9'

services:
  web-frontend-service:
    build: ./frontend/
    container_name: web-frontend
    image: web-frontend-img:latest
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.webfrontend.rule=Host(`site.connectifydigital.com.br`)"  # Substitua pelo seu domínio
      - "traefik.http.routers.webfrontend.entrypoints=web,websecure"
      - "traefik.http.routers.webfrontend.tls=true"
      - "traefik.http.routers.webfrontend.tls.certresolver=leresolver"
    networks:
      - minha_rede

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_HOST=db
      - PMA_PORT=3306
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.phpmyadmin.rule=Host(`phpmyadmin.connectifydigital.com.br`)"  # Substitua pelo seu domínio
      - "traefik.http.routers.phpmyadmin.entrypoints=web,websecure"
      - "traefik.http.routers.phpmyadmin.tls=true"
      - "traefik.http.routers.phpmyadmin.tls.certresolver=leresolver"
    networks:
      - minha_rede

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: example_db
      MYSQL_USER: example_user
      MYSQL_PASSWORD: example_pass
      networks:
      - minha_rede


networks:
  minha_rede:
    name: minha_rede
    external: true