version: '3.9'

services:
  web-frontend-service:
    build: ./frontend/
    container_name: web-frontend
    image: web-frontend-img:latest
    cpus: 1
    mem_limit: 596M
    ports:
      - "8080:80"
    networks:
      - webApp

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "6060:80"
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
    networks:
      - webApp

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: example_db
      MYSQL_USER: example_user
      MYSQL_PASSWORD: example_pass
    networks:
      - webApp

  mautic:
    image: mautic/mautic
    container_name: mautic
    ports:
      - "8081:80"
    environment:
      MYSQL_HOST: db
      MYSQL_USER: example_user
      MYSQL_PASSWORD: example_pass
      MYSQL_DATABASE: example_db
      MAUTIC_DB_HOST: db
      MAUTIC_DB_PORT: 3306
    volumes:
      - mautic_data:/var/www/html
    networks:
      - webApp
    depends_on:
      - db

networks:
  webApp:
    driver: bridge

volumes:
  mautic_data: