version: '3.9'

services:
  web-frontend-service:
    build: ./frontend/
    container_name: web-frontend
    image: web-frontend-img:latest
    networks:
      - npm_public
    ports:
      - 8087:80

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_HOST=db
      - PMA_PORT=3306
    networks:
      - npm_public

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: example_db
      MYSQL_USER: example_user
      MYSQL_PASSWORD: example_pass
    networks:
      - npm_public

networks:
  npm_public:
    name: npm_public
    external: true
